name: Continious deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: Push files
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
        
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          # ftp server
          server: ${{ secrets.FTP_SITE }}
          # ftp username
          username: ${{ secrets.FTP_USERNAME }}
          # ftp password
          password: ${{ secrets.FTP_PASSWD }}
          port: 21 
          log-level: verbose
